//
//  AppDelegate.m
//  HppleDemo
//
//  Created by R0CKSTAR on 15/7/9.
//
//

#import "AppDelegate.h"
#import "TFHpple.h"
#import "AFNetworking.h"
#import "Base64.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    NSMutableString *log = [NSMutableString new];
    __block int j = 0;
    for (int page = 1; page < 85; page++) {
        AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
        manager.responseSerializer = [AFHTTPResponseSerializer new];
        NSDictionary *parameters = @{@"__EVENTTARGET": @"ctl00$ContentPlaceHolder1$anp",
                                     @"__EVENTARGUMENT": @(page),
                                     @"__VIEWSTATE": @"/wEPDwUKLTkyMDIzMjU3OA9kFgJmD2QWAgIDD2QWBgIDDxYCHgdWaXNpYmxlaGQCCQ8PZBYCHgdvbmZvY3VzBQ10aGlzLnZhbHVlPScnZAIPD2QWHGYPFgQeC18hSXRlbUNvdW50AhweDERhdGFTb3VyY2VJRGUWOGYPZBYCZg8VAgE1DeiLueaenCBpUGhvbmVkAgEPZBYCZg8VAgIyMgbkuInmmJ9kAgIPZBYCZg8VAgE2CeivuuWfuuS6mmQCAw9kFgJmDxUCAjE3A0hUQ2QCBA9kFgJmDxUCAjIxDOe0ouWwvOaJi+acumQCBQ9kFgJmDxUCAjc4AkxHZAIGD2QWAmYPFQICMTYM5pGp5omY572X5ouJZAIHD2QWAmYPFQICMjQG6buR6I6TZAIID2QWAmYPFQICMjMG5bCP57GzZAIJD2QWAmYPFQICODQG5Y2O5Li6ZAIKD2QWAmYPFQICMTgG6IGU5oOzZAILD2QWAmYPFQICNjYG5Lit5YW0ZAIMD2QWAmYPFQICNjkG6YW35rS+ZAIND2QWAmYPFQICMjUG6a2F5pePZAIOD2QWAmYPFQICODkET1BQT2QCDw9kFgJmDxUCAjE5CeatpeatpemrmGQCEA9kFgJmDxUCAjg3BumHkeeri2QCEQ9kFgJmDxUCAjg1A1RDTGQCEg9kFgJmDxUCAjY4BuWkqeivrWQCEw9kFgJmDxUCAjg4BuacteWUr2QCFA9kFgJmDxUCAzE0OQbmtbfkv6FkAhUPZBYCZg8VAgMxNzMG576O5Zu+ZAIWD2QWAmYPFQICNjcG5aSP5pmuZAIXD2QWAmYPFQICOTAJ6aOe5Yip5rWmZAIYD2QWAmYPFQICODYJ5aSa5pmu6L6+ZAIZD2QWAmYPFQIDMTc1BumUpOWtkGQCGg9kFgJmDxUCAjkxBue0oueIsWQCGw9kFgJmDxUCAjgwBuWFtuWug2QCAQ8WBB8CAgwfA2UWGGYPZBYCZg8VAgIyMAvoi7nmnpwgaVBhZGQCAQ9kFgJmDxUCAzExNgbkuInmmJ9kAgIPZBYCZg8VAgMxMTkG6IGU5oOzZAIDD2QWAmYPFQIDMTIyBuWNjuehlWQCBA9kFgJmDxUCAzEyMwbljY7kuLpkAgUPZBYCZg8VAgMxMTgG5b6u6L2vZAIGD2QWAmYPFQIDMTUzBuiwt+atjGQCBw9kFgJmDxUCAzEyNAblro/nooFkAggPZBYCZg8VAgMxMjES57Si5bC85bmz5p2/55S16ISRZAIJD2QWAmYPFQIDMTE3DOaRqeaJmOe9l+aLiWQCCg9kFgJmDxUCAzEyMANIVENkAgsPZBYCZg8VAgMxNTEM6YW35q+U6a2U5pa5ZAICDxYEHwICDx8DZRYeZg9kFgJmDxUCAzE1NQxBcHBsZS/oi7nmnpxkAgEPZBYCZg8VAgMxNTYIVGhpbmtQYWRkAgIPZBYCZg8VAgMxNjAG5LiJ5pifZAIDD2QWAmYPFQIDMTYyBuaItOWwlGQCBA9kFgJmDxUCAzE4MQzmuIXljY7lkIzmlrlkAgUPZBYCZg8VAgMxNjMG5a6P56KBZAIGD2QWAmYPFQIDMTY0BuelnuiIn2QCBw9kFgJmDxUCAzE2NgbkuJzoip1kAggPZBYCZg8VAgMxNjgG5oOg5pmuZAIJD2QWAmYPFQIDMTcwBuiBlOaDs2QCCg9kFgJmDxUCAzE3MQbljY7noZVkAgsPZBYCZg8VAgMxNjUJ5a+M5aOr6YCaZAIMD2QWAmYPFQIDMTYxBuW+ruaYn2QCDQ9kFgJmDxUCAzE3MgbntKLlsLxkAg4PZBYCZg8VAgMxNzQG5piC6L6+ZAIDDxYEHwICCB8DZRYQZg9kFgJmDxUCATUN6Iu55p6cIGlQaG9uZWQCAQ9kFgJmDxUCAjIwC+iLueaenCBpUGFkZAICD2QWAmYPFQIDMTI4EeiLueaenCBpUG9kIHRvLi4uZAIDD2QWAmYPFQIDMTI5EeiLueaenCBpUG9kIG5hLi4uZAIED2QWAmYPFQIDMTMwEeiLueaenCBpUG9kIHNoLi4uZAIFD2QWAmYPFQIDMTMxEeiLueaenCBpUG9kIGNsLi4uZAIGD2QWAmYPFQIDMjA5DUFQUExFIFdBVEMuLi5kAgcPZBYCZg8VAgMxNTUMQXBwbGUv6Iu55p6cZAIEDxYEHwICAx8DZRYGZg9kFgJmDxUCAzEyNwRYQk9YZAIBD2QWAmYPFQIDMTI1D+e0ouWwvOa4uOaIj+acumQCAg9kFgJmDxUCAzEyNgnku7vlpKnloIJkAgUPFgQfAgIIHwNlFhBmD2QWAmYPFQIDMTg3BuiBlOaDs2QCAQ9kFgJmDxUCAzE4OAlBbGllbndhcmVkAgIPZBYCZg8VAgMxODkG5oi05bCUZAIDD2QWAmYPFQIDMTkwBEFjZXJkAgQPZBYCZg8VAgMxOTEG5Y2O56GVZAIFD2QWAmYPFQIDMTkyBuaDoOaZrmQCBg9kFgJmDxUCAzE5MwbkuInmmJ9kAgcPZBYCZg8VAgMxOTcG6Iu55p6cZAIGDxYEHwICCx8DZRYWZg9kFgJmDxUCAzE5OAbkuInmmJ9kAgEPZBYCZg8VAgMxOTkJ6aOe5Yip5rWmZAICD2QWAmYPFQIDMjAwA0FPQ2QCAw9kFgJmDxUCAzIwMQRERUxMZAIED2QWAmYPFQIDMjAyAkxHZAIFD2QWAmYPFQIDMjAzBuS8mOa0vmQCBg9kFgJmDxUCAzIwNAJIUGQCBw9kFgJmDxUCAzIwNQRhY2VyZAIID2QWAmYPFQIDMjA2BuiBlOaDs2QCCQ9kFgJmDxUCAzIwNwRCZW5RZAIKD2QWAmYPFQIDMjA4DOWFtuS7luWTgeeJjGQCBw8WBB8CAgEfA2UWAmYPZBYCZg8VAgMxOTQFSW50ZWxkAggPFgQfAgIIHwNlFhBmD2QWAmYPFQIDMjE0E+mHkeWjq+mhv0tpbmdzdG8uLi5kAgEPZBYCZg8VAgMyMTUO6Iux54m55bCUaW50ZWxkAgIPZBYCZg8VAgMyMTYN6Zeq6L+qU2FuRGlza2QCAw9kFgJmDxUCAzIxNw3kuJzoip1UT1NISUJBZAIED2QWAmYPFQIDMjE4DeS4ieaYn1NBTVNVTkdkAgUPZBYCZg8VAgMyMTkM576O5YWJTWljcm9uZAIGD2QWAmYPFQIDMjIwDeiDnOWIm0tpbmdtYXhkAgcPZBYCZg8VAgMyMjkY5YW25LuW5ZOB54mM77yI56Gs55uY77yJZAIJDxYEHwICBh8DZRYMZg9kFgJmDxUCAzIyNhPph5Hlo6vpob9LaW5nc3RvLi4uZAIBD2QWAmYPFQIDMjI4DeS4ieaYn1NBTVNVTkdkAgIPZBYCZg8VAgMyMjQM5a6H5567QXBhY2VyZAIDD2QWAmYPFQIDMjIzC+WogeWImkFEQVRBZAIED2QWAmYPFQIDMjIyDeeOsOS7o0h5dW5kYWlkAgUPZBYCZg8VAgMyMjUY5YW25a6D5ZOB54mM77yI5YaF5a2Y77yJZAIKDxYEHwICCB8DZRYQZg9kFgJmDxUHATECNzMVMjAxNDEwMjUwNDIzMTA1NDguanBnGeiLueaenCBpUGhvbmUgNCDmsLTotKfniYgCNzMZ6Iu55p6cIGlQaG9uZSA0IOawtOi0p+eJiAMzNTBkAgEPZBYCZg8VBwEyBDM3NTAVMjAxNTAzMjcxMjUzMTM4NjYuanBnEuiBlOaDs+WQr+WkqSBCNDU1MAQzNzUwEuiBlOaDs+WQr+WkqSBCNDU1MAM1MDBkAgIPZBYCZg8VBwEzBDM5NTAVMjAxNTAzMjcwMzEzMzg2MTMuanBnI+iBlOaDs+aJrOWkqSBBNjAwMGstMDDvvIhpMyA0MTYw77yJBDM5NTAj6IGU5oOz5oms5aSpIEE2MDAway0wMO+8iGkzIDQxNjDvvIkEMTA4MGQCAw9kFgJmDxUHATQENDE1MBUyMDE1MDMyNzA2MDIyNTUwOC5wbmcY5oOg5pmuUGF2aWxpb24gNTAwLTQ3MWNuBDQxNTAY5oOg5pmuUGF2aWxpb24gNTAwLTQ3MWNuBDI2MTBkAgQPZBYCZg8VBwE1BDEzOTkVMjAxNDEwMjUwNDI0NDEzMTYuanBnF+iLueaenCBpUGhvbmUgNCAg5Zu96KGMBDEzOTkX6Iu55p6cIGlQaG9uZSA0ICDlm73ooYwDMzUwZAIFD2QWAmYPFQcBNgQzNzUyFTIwMTUwMzI3MDEwMDE3NDkxLmpwZyHogZTmg7PmiazlpKkgQTQ2MDBLLTAw77yIRzMyNTDvvIkEMzc1MiHogZTmg7PmiazlpKkgQTQ2MDBLLTAw77yIRzMyNTDvvIkDNzA1ZAIGD2QWAmYPFQcBNwI4MBUyMDE0MTEwNDEwNDQ0NDUyNi5qcGca6Iu55p6cIGlQaG9uZSA0cyDmsLTotKfniYgCODAa6Iu55p6cIGlQaG9uZSA0cyDmsLTotKfniYgDNTUwZAIHD2QWAmYPFQcBOAQ0MTUyFTIwMTUwMzI3MDYzNTM2MzY5LnBuZyfmg6Dmma5FbGl0ZURlc2sgODAwIEcxIFNGRu+8iEo4RjgwUEHvvIkENDE1Mifmg6Dmma5FbGl0ZURlc2sgODAwIEcxIFNGRu+8iEo4RjgwUEHvvIkEMjYxMGQCCw8WBB8CAgYfA2UWDGYPZBYCZg8VAgI2MRjnv7zplIvnvZHkuqTmmJPlronlhajlkJdkAgEPZBYCZg8VAgI2Mifnv7zplIvnvZHlm57mlLbnmoTml6fmiYvmnLrlpoLkvZXlpITnkIZkAgIPZBYCZg8VAgI2Mxzpgq7lr4TkuYvliY3pnIDopoHlgZrku4DkuYg/ZAIDD2QWAmYPFQICNjQe5pS25Yiw6LSn5beu5byC5LiN56ym5oCO5LmI5YqeZAIED2QWAmYPFQICNjUf5oiR5Lus6ZyA6KaB5rWL6K+V5omL5py65LuA5LmIP2QCBQ9kFgJmDxUCAzE1MhjmsqHmnInmiJHnmoTmiYvmnLrlnovlj7dkAgwPFgQfAgIcHwNlFjhmD2QWBgIBDw8WAh4EVGV4dAUBNWRkAgMPDxYCHwQFATBkZAIFDxYCHwQFSTxsaT48YSBzdHlsZT0iY29sb3I6UmVkOyIgaHJlZj0icHJvbGlzdC05My01Lmh0bWwiPuiLueaenCBpUGhvbmU8L2E+PC9saT5kAgEPZBYGAgEPDxYCHwQFAjIyZGQCAw8PFgIfBAUBMWRkAgUPFgIfBAVDPGxpPjxhIHN0eWxlPSJjb2xvcjpSZWQ7IiBocmVmPSJwcm9saXN0LTkzLTIyLmh0bWwiPuS4ieaYnzwvYT48L2xpPmQCAg9kFgYCAQ8PFgIfBAUBNmRkAgMPDxYCHwQFATJkZAIFDxYCHwQFRTxsaT48YSBzdHlsZT0iY29sb3I6UmVkOyIgaHJlZj0icHJvbGlzdC05My02Lmh0bWwiPuivuuWfuuS6mjwvYT48L2xpPmQCAw9kFgYCAQ8PFgIfBAUCMTdkZAIDDw8WAh8EBQEzZGQCBQ8WAh8EBUA8bGk+PGEgc3R5bGU9ImNvbG9yOlJlZDsiIGhyZWY9InByb2xpc3QtOTMtMTcuaHRtbCI+SFRDPC9hPjwvbGk+ZAIED2QWBgIBDw8WAh8EBQIyMWRkAgMPDxYCHwQFATRkZAIFDxYCHwQFSTxsaT48YSBzdHlsZT0iY29sb3I6UmVkOyIgaHJlZj0icHJvbGlzdC05My0yMS5odG1sIj7ntKLlsLzmiYvmnLo8L2E+PC9saT5kAgUPZBYGAgEPDxYCHwQFAjc4ZGQCAw8PFgIfBAUBNWRkAgUPFgIfBAU/PGxpPjxhIHN0eWxlPSJjb2xvcjpSZWQ7IiBocmVmPSJwcm9saXN0LTkzLTc4Lmh0bWwiPkxHPC9hPjwvbGk+ZAIGD2QWBgIBDw8WAh8EBQIxNmRkAgMPDxYCHwQFATZkZAIFDxYCHwQFNjxsaT48YSBocmVmPSJwcm9saXN0LTkzLTE2Lmh0bWwiPuaRqeaJmOe9l+aLiTwvYT48L2xpPmQCBw9kFgYCAQ8PFgIfBAUCMjRkZAIDDw8WAh8EBQE3ZGQCBQ8WAh8EBTA8bGk+PGEgaHJlZj0icHJvbGlzdC05My0yNC5odG1sIj7pu5HojpM8L2E+PC9saT5kAggPZBYGAgEPDxYCHwQFAjIzZGQCAw8PFgIfBAUBOGRkAgUPFgIfBAUwPGxpPjxhIGhyZWY9InByb2xpc3QtOTMtMjMuaHRtbCI+5bCP57GzPC9hPjwvbGk+ZAIJD2QWBgIBDw8WAh8EBQI4NGRkAgMPDxYCHwQFATlkZAIFDxYCHwQFMDxsaT48YSBocmVmPSJwcm9saXN0LTkzLTg0Lmh0bWwiPuWNjuS4ujwvYT48L2xpPmQCCg9kFgYCAQ8PFgIfBAUCMThkZAIDDw8WAh8EBQIxMGRkAgUPFgIfBAUwPGxpPjxhIGhyZWY9InByb2xpc3QtOTMtMTguaHRtbCI+6IGU5oOzPC9hPjwvbGk+ZAILD2QWBgIBDw8WAh8EBQI2NmRkAgMPDxYCHwQFAjExZGQCBQ8WAh8EBTA8bGk+PGEgaHJlZj0icHJvbGlzdC05My02Ni5odG1sIj7kuK3lhbQ8L2E+PC9saT5kAgwPZBYGAgEPDxYCHwQFAjY5ZGQCAw8PFgIfBAUCMTJkZAIFDxYCHwQFMDxsaT48YSBocmVmPSJwcm9saXN0LTkzLTY5Lmh0bWwiPumFt+a0vjwvYT48L2xpPmQCDQ9kFgYCAQ8PFgIfBAUCMjVkZAIDDw8WAh8EBQIxM2RkAgUPFgIfBAUwPGxpPjxhIGhyZWY9InByb2xpc3QtOTMtMjUuaHRtbCI+6a2F5pePPC9hPjwvbGk+ZAIOD2QWBgIBDw8WAh8EBQI4OWRkAgMPDxYCHwQFAjE0ZGQCBQ8WAh8EBS48bGk+PGEgaHJlZj0icHJvbGlzdC05My04OS5odG1sIj5PUFBPPC9hPjwvbGk+ZAIPD2QWBgIBDw8WAh8EBQIxOWRkAgMPDxYCHwQFAjE1ZGQCBQ8WAh8EBTM8bGk+PGEgaHJlZj0icHJvbGlzdC05My0xOS5odG1sIj7mraXmraXpq5g8L2E+PC9saT5kAhAPZBYGAgEPDxYCHwQFAjg3ZGQCAw8PFgIfBAUCMTZkZAIFDxYCHwQFMDxsaT48YSBocmVmPSJwcm9saXN0LTkzLTg3Lmh0bWwiPumHkeerizwvYT48L2xpPmQCEQ9kFgYCAQ8PFgIfBAUCODVkZAIDDw8WAh8EBQIxN2RkAgUPFgIfBAUtPGxpPjxhIGhyZWY9InByb2xpc3QtOTMtODUuaHRtbCI+VENMPC9hPjwvbGk+ZAISD2QWBgIBDw8WAh8EBQI2OGRkAgMPDxYCHwQFAjE4ZGQCBQ8WAh8EBTA8bGk+PGEgaHJlZj0icHJvbGlzdC05My02OC5odG1sIj7lpKnor608L2E+PC9saT5kAhMPZBYGAgEPDxYCHwQFAjg4ZGQCAw8PFgIfBAUCMTlkZAIFDxYCHwQFMDxsaT48YSBocmVmPSJwcm9saXN0LTkzLTg4Lmh0bWwiPuacteWUrzwvYT48L2xpPmQCFA9kFgYCAQ8PFgIfBAUDMTQ5ZGQCAw8PFgIfBAUCMjBkZAIFDxYCHwQFMTxsaT48YSBocmVmPSJwcm9saXN0LTkzLTE0OS5odG1sIj7mtbfkv6E8L2E+PC9saT5kAhUPZBYGAgEPDxYCHwQFAzE3M2RkAgMPDxYCHwQFAjIxZGQCBQ8WAh8EBTE8bGk+PGEgaHJlZj0icHJvbGlzdC05My0xNzMuaHRtbCI+576O5Zu+PC9hPjwvbGk+ZAIWD2QWBgIBDw8WAh8EBQI2N2RkAgMPDxYCHwQFAjIyZGQCBQ8WAh8EBTA8bGk+PGEgaHJlZj0icHJvbGlzdC05My02Ny5odG1sIj7lpI/mma48L2E+PC9saT5kAhcPZBYGAgEPDxYCHwQFAjkwZGQCAw8PFgIfBAUCMjNkZAIFDxYCHwQFMzxsaT48YSBocmVmPSJwcm9saXN0LTkzLTkwLmh0bWwiPumjnuWIqea1pjwvYT48L2xpPmQCGA9kFgYCAQ8PFgIfBAUCODZkZAIDDw8WAh8EBQIyNGRkAgUPFgIfBAUzPGxpPjxhIGhyZWY9InByb2xpc3QtOTMtODYuaHRtbCI+5aSa5pmu6L6+PC9hPjwvbGk+ZAIZD2QWBgIBDw8WAh8EBQMxNzVkZAIDDw8WAh8EBQIyNWRkAgUPFgIfBAUxPGxpPjxhIGhyZWY9InByb2xpc3QtOTMtMTc1Lmh0bWwiPumUpOWtkDwvYT48L2xpPmQCGg9kFgYCAQ8PFgIfBAUCOTFkZAIDDw8WAh8EBQIyNmRkAgUPFgIfBAUwPGxpPjxhIGhyZWY9InByb2xpc3QtOTMtOTEuaHRtbCI+57Si54ixPC9hPjwvbGk+ZAIbD2QWBgIBDw8WAh8EBQI4MGRkAgMPDxYCHwQFAjI3ZGQCBQ8WAh8EBTA8bGk+PGEgaHJlZj0icHJvbGlzdC05My04MC5odG1sIj7lhbblroM8L2E+PC9saT5kAg0PZBYEAgMPFgQfAgIUHwNlFihmD2QWAmYPFQUEMjAyOBUyMDE0MDYwNTA0MzI0OTU3OS5wbmce5Lit5YW0TnViaWEgWjVTIG1pbmkg5Yqq5q+U5LqaHuS4reWFtE51YmlhIFo1UyBtaW5pIOWKquavlOS6mgMyNDBkAgEPZBYCZg8VBQQxMzA5FTIwMTMwNTE1MDkxNzQ4MDU3LmpwZwlIVEMgVDUyOFcJSFRDIFQ1MjhXAzExMGQCAg9kFgJmDxUFBDI2NTAVMjAxNDA2MTAwMzM3MjExODguanBnFeS4ieaYnyBHYWxheHkgUzUgRzkwMBXkuInmmJ8gR2FsYXh5IFM1IEc5MDAEMTIwMGQCAw9kFgJmDxUFBDEyOTEVMjAxMzAzMDcwMjEwMjU2ODMuanBnIkhUQyBUMzI4ZO+8iOaWsOa4tOacm1bvvInnlLXkv6HniYgiSFRDIFQzMjhk77yI5paw5ri05pybVu+8ieeUteS/oeeJiAMxMDBkAgQPZBYCZg8VBQM4MDkVMjAxMzA1MTMwNDI5NDYxMDcuanBnFeiLueaenCBpUGhvbmUgM0cgMuS7oxXoi7nmnpwgaVBob25lIDNHIDLku6MCNTBkAgUPZBYCZg8VBQM3NTQVMjAxMzA1MTQwMjI4MTk4NjUuanBnDeivuuWfuuS6miBFNzEN6K+65Z+65LqaIEU3MQIzMGQCBg9kFgJmDxUFBDE0MjYVMjAxMzEyMTMwNTAyMDc3NjQuanBnC+WNjuS4uiBHNTIwC+WNjuS4uiBHNTIwAzEwMGQCBw9kFgJmDxUFAzU1NxUyMDEzMDUxNTA5NDE0NDEyOC5qcGcW6K+65Z+65LqaIFB1cmVWaWV3IDgwOBbor7rln7rkupogUHVyZVZpZXcgODA4AzQwMGQCCA9kFgJmDxUFBDE0NTkVMjAxMzEyMjAxMTA5MDkyOTcuanBnFeWNjuS4uuiNo+iAgDMgSE4zLVUwMRXljY7kuLrojaPogIAzIEhOMy1VMDEDMTUwZAIJD2QWAmYPFQUEMTQ2OBUyMDEzMTIyNzA0MzAwODE0MC5qcGcNdml2byBYMVMgWDFTdA12aXZvIFgxUyBYMVN0AzIwMGQCCg9kFgJmDxUFBDE0MTYVMjAxMzA5MTExMDAzMjYxNTEuanBnLOS4ieaYnyBJOTE5MCBJOTE5MiBJOTE5OO+8iEdhbGF4eSBTNCBNaW5p77yJLOS4ieaYnyBJOTE5MCBJOTE5MiBJOTE5OO+8iEdhbGF4eSBTNCBNaW5p77yJAzMwMGQCCw9kFgJmDxUFBDE0NTIVMjAxNDA2MDUwMzQ4Mzk5ODMucG5nI+e0ouWwvFhwZXJpYSBTUO+8iE0zNWgg6IGU6YCa54mI77yJI+e0ouWwvFhwZXJpYSBTUO+8iE0zNWgg6IGU6YCa54mI77yJAzIwMGQCDA9kFgJmDxUFBDE0NzQVMjAxMzEyMjYxMDQ4NDgxNzguanBnCk9QUE8gUjgwOVQKT1BQTyBSODA5VAMyNTBkAg0PZBYCZg8VBQM1NzAVMjAxMzA1MTUwOTMzNDQzNTQuanBnE+ivuuWfuuS6miBMdW1pYSA4MDAT6K+65Z+65LqaIEx1bWlhIDgwMAI3MGQCDg9kFgJmDxUFBDEzMDAVMjAxMzAzMTEwNTI2NDcwMTAuanBnH0hUQyBUNTI4RO+8iE9uZSBTQy/nlLXkv6HniYjvvIkfSFRDIFQ1MjhE77yIT25lIFNDL+eUteS/oeeJiO+8iQMxMTBkAg8PZBYCZg8VBQQxNDYyFTIwMTQwMTI0MDQzNzIzOTk3LmpwZyRMRyBGMjQwSy9TL0wgRTk4OO+8iE9wdGltdXMgRyBQcm/vvIkkTEcgRjI0MEsvUy9MIEU5ODjvvIhPcHRpbXVzIEcgUHJv77yJAzI2MGQCEA9kFgJmDxUFBDEzOTEVMjAxMzEwMjgwOTU0MTAxMTYuanBnC+iBlOaDs0s4NjBpC+iBlOaDs0s4NjBpAzE1MGQCEQ9kFgJmDxUFBDEyMDcVMjAxMzA1MTQwMzQwNTA5MjEuanBnHue0ouWwvExUMjZ377yIWHBlcmlhIGFjcm8gU++8iR7ntKLlsLxMVDI2d++8iFhwZXJpYSBhY3JvIFPvvIkDMTAwZAISD2QWAmYPFQUEMTM4ORUyMDEzMDUyMTAzMjQyNTMwMy5qcGcJSFRDIFQzMjl3CUhUQyBUMzI5dwMxMDBkAhMPZBYCZg8VBQM1NTUVMjAxMzA2MDYwOTM4MTA5MzMuanBnHuivuuWfuuS6miBMdW1pYSA4MDBjIOeUteS/oeeJiB7or7rln7rkupogTHVtaWEgODAwYyDnlLXkv6HniYgCODBkAgUPDxYEHhBDdXJyZW50UGFnZUluZGV4AgkeC1JlY29yZGNvdW50ApsNZGRk/BA0FaSw0wJPqsItdQdaIzB2CSI=",
                                     @"__VIEWSTATEGENERATOR": @"8A9F8A8E",
                                     @"__EVENTVALIDATION": @"/wEWAwKOxYyXCALjiMfxCgKb69XMB7husgRM4FAZGhSjBwN17tKPoUYj",
                                     @"ctl00$inputtit": @"请输入您的品牌和机型,看看您的宝贝还值多少钱？",
                                     @"ctl00$ContentPlaceHolder1$anp_input": @"1",
                                     @"hiddenInputToUpdateATBuffer_CommonToolkitScripts": @"1"};
        [manager POST:@"http://www.yifone.com/prolist.aspx?fid=93" parameters:parameters success:^(AFHTTPRequestOperation *operation, id responseObject) {
            TFHpple *doc      = [[TFHpple alloc] initWithHTMLData:responseObject];
            NSArray *elements = [doc searchWithXPathQuery:@"//div[@id='ctl00_ContentPlaceHolder1_divY']/ul/li/a"];
            for (int i = 0; i < [elements count]; i++) {
                TFHppleElement *e = [elements objectAtIndex:i];
                NSString *pid = [[[e objectForKey:@"href"] stringByDeletingPathExtension] stringByReplacingOccurrencesOfString:@"prodetails-" withString:@""];
                NSString *name = nil;
                for (TFHppleElement *t in e.children) {
                    if ([[t tagName] isEqualToString:@"img"]) {
                        name = [[t objectForKey:@"alt"] stringByReplacingOccurrencesOfString:@"手机回收" withString:@""];
                        break;
                    }
                }
                j++;
                NSString *URL = [NSString stringWithFormat:@"http://www.yifone.com/NewASHX/getQybProPrice.ashx?clid=24,73,74,57,81,39,17,27,85,64,13,78,88,91,10,34,&pid=%@", pid];
                [manager GET:URL parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
                    NSString *price = [[NSString alloc] initWithData:responseObject encoding:NSUTF8StringEncoding];
                    [log appendString:name];
                    [log appendString:@";"];
                    [log appendString:price];
                    [log appendString:@"\n"];
                    j--;
                    if (j == 0) {
                        int a = 0;
                        a++;
                    }
                } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
                    j--;
                    if (j == 0) {
                        int a = 0;
                        a++;
                    }
                    NSLog(@"Error: %@", error);
                }];
            }
        } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            NSLog(@"Error: %@", error);
        }];
    }
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        for (int t = 0; t < 10000000; t++) {
            sleep(1);
        }
    });
    self.window = [UIWindow new];
    [self.window makeKeyAndVisible];
    return YES;
}

@end
